#' @name LogicalFilterState
#' @title `FilterState` object for logical variable
#' @description Manages choosing a logical state
#' @docType class
#' @keywords internal
#'
#'
#' @examples
#' filter_state <- teal.slice:::LogicalFilterState$new(
#'   x = sample(c(TRUE, FALSE, NA), 10, replace = TRUE),
#'   varname = "x",
#'   dataname = "data",
#'   extract_type = character(0)
#' )
#' shiny::isolate(filter_state$get_call())
#' filter_state$set_state(
#'   filter_var(dataname = "data", varname = "x", selected = TRUE, keep_na = TRUE)
#' )
#' shiny::isolate(filter_state$get_call())
#'
#' \dontrun{
#' # working filter in an app
#' library(shiny)
#' library(shinyjs)
#'
#' data_logical <- c(sample(c(TRUE, FALSE), 10, replace = TRUE), NA)
#' fs <- teal.slice:::LogicalFilterState$new(
#'   x = data_logical,
#'   dataname = "data",
#'   varname = "x",
#'   selected = FALSE,
#'   keep_na = TRUE
#' )
#'
#' ui <- fluidPage(
#'   useShinyjs(),
#'   include_css_files(pattern = "filter-panel"),
#'   include_js_files(pattern = "count-bar-labels"),
#'   column(4, div(
#'     h4("LogicalFilterState"),
#'     fs$ui("fs")
#'   )),
#'   column(4, div(
#'     id = "outputs", # div id is needed for toggling the element
#'     h4("Condition (i.e. call)"), # display the subsetting call generated by this FilterState
#'     textOutput("condition_logical"), br(),
#'     h4("Unformatted state"), # display raw filter state
#'     textOutput("unformatted_logical"), br(),
#'     h4("Formatted state"), # display human readable filter state
#'     textOutput("formatted_logical"), br()
#'   )),
#'   column(4, div(
#'     h4("Programmatic filter control"),
#'     actionButton("button1_logical", "set drop NA", width = "100%"), br(),
#'     actionButton("button2_logical", "set keep NA", width = "100%"), br(),
#'     actionButton("button3_logical", "set a selection", width = "100%"), br(),
#'     actionButton("button0_logical", "set initial state", width = "100%"), br()
#'   ))
#' )
#'
#' server <- function(input, output, session) {
#'   fs$server("fs")
#'   output$condition_logical <- renderPrint(fs$get_call())
#'   output$formatted_logical <- renderText(fs$format())
#'   output$unformatted_logical <- renderPrint(fs$get_state())
#'   # modify filter state programmatically
#'   observeEvent(
#'     input$button1_logical,
#'     fs$set_state(filter_var(dataname = "data", varname = "x", keep_na = FALSE))
#'   )
#'   observeEvent(
#'     input$button2_logical,
#'     fs$set_state(filter_var(dataname = "data", varname = "x", keep_na = TRUE))
#'   )
#'   observeEvent(
#'     input$button3_logical,
#'     fs$set_state(filter_var(dataname = "data", varname = "x", selected = TRUE))
#'   )
#'   observeEvent(
#'     input$button0_logical,
#'     fs$set_state(
#'       filter_var(dataname = "data", varname = "x", selected = FALSE, keep_na = TRUE)
#'     )
#'   )
#' }
#'
#' if (interactive()) {
#'   shinyApp(ui, server)
#' }
#' }
#'
LogicalFilterState <- R6::R6Class( # nolint
  "LogicalFilterState",
  inherit = FilterState,

  # public methods ----
  public = list(

    #' @description
    #' Initialize a `FilterState` object
    #'
    #' @param x (`logical`)\cr
    #'   values of the variable used in filter
    #' @param x_reactive (`reactive`)\cr
    #'   returning vector of the same type as `x`. Is used to update
    #'   counts following the change in values of the filtered dataset.
    #'   If it is set to `reactive(NULL)` then counts based on filtered
    #'   dataset are not shown.
    #' @param dataname (`character(1)`)\cr
    #'   optional name of dataset where `x` is taken from. Must be specified
    #'   if `extract_type` argument is not empty.
    #' @param varname (`character(1)`)\cr
    #'   name of the variable.
    #' @param choices (`atomic`, `NULL`)\cr
    #'   vector specifying allowed selection values
    #' @param multiple (`logical(1)`)\cr
    #'   flag specifying whether the `FilterState` more than one value can be selected
    #' @param selected (`atomic`, `NULL`)\cr
    #'   vector specifying selection
    #' @param keep_na (`logical(1)`, `NULL`)\cr
    #'   flag specifying whether to keep missing values
    #' @param keep_inf (`logical(1)`, `NULL`)\cr
    #'   flag specifying whether to keep infinite values
    #' @param fixed (`logical(1)`)\cr
    #'   flag specifying whether the `FilterState` is initiated fixed
    #' @param disabled (`logical(1)`)\cr
    #'   flag specifying whether the `FilterState` is initiated disabled
    #' @param extract_type (`character(0)`, `character(1)`)\cr
    #' whether condition calls should be prefixed by dataname. Possible values:
    #' \itemize{
    #' \item{`character(0)` (default)}{ `varname` in the condition call will not be prefixed}
    #' \item{`"list"`}{ `varname` in the condition call will be returned as `<dataname>$<varname>`}
    #' \item{`"matrix"`}{ `varname` in the condition call will be returned as `<dataname>[, <varname>]`}
    #' }
    #' @param ... additional arguments to be saved as a list in `private$extras` field
    #'
    initialize = function(x,
                          x_reactive = reactive(NULL),
                          dataname,
                          varname,
                          choices = NULL,
                          multiple = NULL,
                          selected = NULL,
                          keep_na = NULL,
                          keep_inf = NULL,
                          fixed = FALSE,
                          disabled = FALSE,
                          extract_type = character(0),
                          ...) {
      checkmate::assert_logical(x)
      checkmate::assert_class(x_reactive, "reactive")
      checkmate::assert_flag(selected, null.ok = TRUE)

      if (is.null(multiple)) multiple <- TRUE # Set default behavior of multiple variable to TRUE.
      args <- list(
        x = x,
        x_reactive = x_reactive,
        dataname = dataname,
        varname = varname,
        multiple = multiple,
        keep_na = keep_na,
        keep_inf = keep_inf,
        fixed = fixed,
        disabled = disabled,
        extract_type = extract_type
      )
      args <- append(args, list(...))
      do.call(super$initialize, args)

      private$set_choices(choices)
      private$set_selected(selected)

      df <- factor(x, levels = c(TRUE, FALSE))
      tbl <- table(df)
      private$set_choices_counts(tbl)

      invisible(self)
    },

    #' @description
    #' Returns reproducible condition call for current selection.
    #' For `LogicalFilterState` it's a `!<varname>` or `<varname>` and optionally
    #' `is.na(<varname>)`
    #' @param dataname name of data set; defaults to `private$dataname`
    #' @return (`call`)
    #'
    get_call = function(dataname) {
      if (isFALSE(private$is_any_filtered())) {
        return(NULL)
      }
      if (missing(dataname)) dataname <- private$dataname
      varname <- private$get_varname_prefixed(dataname)
      choices <- private$get_selected()
      n_choices <- length(choices)

      filter_call <-
        if (n_choices == 1 && choices) {
          private$get_varname_prefixed(dataname)
        } else if (n_choices == 1 && !choices) {
          call("!", private$get_varname_prefixed(dataname))
        } else {
          call("%in%", private$get_varname_prefixed(dataname), make_c_call(choices))
        }
      private$add_keep_na_call(filter_call, dataname)
    }
  ),

  # private fields ----

  private = list(
    choices_counts = integer(0),
    set_choices = function(choices) {
      private$choices <- c(TRUE, FALSE)
      invisible(NULL)
    },
    # @description
    # Sets choices_counts private field
    set_choices_counts = function(choices_counts) {
      private$choices_counts <- choices_counts
      invisible(NULL)
    },
    validate_selection = function(value) {
      if (!(checkmate::test_logical(value, any.missing = FALSE, unique = TRUE))) {
        stop(
          sprintf(
            "value of the selection for `%s` in `%s` should be a logical vector of length <= 2",
            private$get_varname(),
            private$get_dataname()
          )
        )
      }

      pre_msg <- sprintf(
        "dataset '%s', variable '%s': ",
        private$get_dataname(),
        private$get_varname()
      )
      check_in_subset(value, private$choices, pre_msg = pre_msg)
    },
    cast_and_validate = function(values) {
      tryCatch(
        expr = {
          values_logical <- as.logical(values)
          if (any(is.na(values_logical))) stop()
        },
        error = function(cond) stop("The array of set values must contain values coercible to logical.")
      )
      values_logical
    },
    remove_out_of_bound_values = function(values) {
      if (length(values) != 1 && !private$multiple) {
        warning("\"values\" is not a vector of length one. The first value will be selected.")
        values <- TRUE
      }
      values
    },

    # Answers the question of whether the current settings and values selected actually filters out any values.
    # @return logical scalar
    is_any_filtered = function() {
      if (private$is_disabled()) {
        FALSE
      } else if (private$is_choice_limited) {
        TRUE
      } else if (all(private$choices_counts > 0)) {
        TRUE
      } else if (isFALSE(all.equal(private$get_selected(), private$choices)) &&
                 !anyNA(private$get_selected(), private$choices)) {
        TRUE
      } else if (!isTRUE(private$get_keep_na()) && private$na_count > 0) {
        TRUE
      } else {
        FALSE
      }
    },

    # shiny modules ----

    # @description
    # UI Module for `EmptyFilterState`.
    # This UI element contains available choices selection and
    # checkbox whether to keep or not keep the `NA` values.
    # @param id (`character(1)`)\cr
    #  id of shiny element
    ui_inputs = function(id) {
      ns <- NS(id)

      countsmax <- private$choices_counts
      countsnow <- countsnow <- if (!is.null(shiny::isolate(private$x_reactive()))) {
        shiny::isolate(unname(table(factor(private$x_reactive(), levels = private$choices))))
      } else {
        NULL
      }

      labels <- countBars(
        inputId = ns("labels"),
        choices = as.character(private$choices),
        countsnow = countsnow,
        countsmax = countsmax
      )
      ui_input <- if (private$multiple) {
        checkboxGroupInput(
          inputId = ns("selection"),
          label = NULL,
          selected = shiny::isolate(as.character(private$get_selected())),
          choiceNames = labels,
          choiceValues = factor(as.character(private$choices), levels = c("TRUE", "FALSE")),
          width = "100%"
        )
      } else {
        radioButtons(
          inputId = ns("selection"),
          label = NULL,
          selected = shiny::isolate(as.character(private$get_selected())),
          choiceNames = labels,
          choiceValues = factor(as.character(private$choices), levels = c("TRUE", "FALSE")),
          width = "100%"
        )
      }
      if (shiny::isolate(private$is_disabled())) ui_input <- shinyjs::disabled(ui_input)
      div(
        div(
          class = "choices_state",
          uiOutput(ns("trigger_visible"), inline = TRUE),
          ui_input
        ),
        private$keep_na_ui(ns("keep_na"))
      )
    },

    # @description
    # Server module
    #
    # @param id (`character(1)`)\cr
    #   an ID string that corresponds with the ID used to call the module's UI function.
    # @return `moduleServer` function which returns `NULL`
    server_inputs = function(id) {
      moduleServer(
        id = id,
        function(input, output, session) {
          # this observer is needed in the situation when private$selected has been
          # changed directly by the api - then it's needed to rerender UI element
          # to show relevant values
          non_missing_values <- reactive(Filter(Negate(is.na), private$x_reactive()))
          output$trigger_visible <- renderUI({
            logger::log_trace(sprintf(
              "LogicalFilterState$server@1 updating count labels in variable: %s , dataname: %s",
              private$varname,
              private$dataname
            ))

            countsnow <- if (!is.null(private$x_reactive())) {
              unname(table(factor(non_missing_values(), levels = private$choices)))
            } else {
              NULL
            }

            updateCountBars(
              inputId = "labels",
              choices = as.character(private$choices),
              countsmax = private$choices_counts,
              countsnow = countsnow
            )
            NULL
          })

          private$observers$seleted_api <- observeEvent(
            ignoreNULL = !private$multiple,
            ignoreInit = TRUE,
            eventExpr = private$get_selected(),
            handlerExpr = {
              if (!setequal(private$get_selected(), input$selection)) {
                if (private$multiple) {
                  updateCheckboxGroupInput(
                    inputId = "selection",
                    selected = private$get_selected()
                  )
                } else {
                  updateRadioButtons(
                    inputId = "selection",
                    selected =  private$get_selected()
                  )
                }

                logger::log_trace(sprintf(
                  "LogicalFilterState$server@1 state of variable %s changed, dataname: %s",
                  private$varname,
                  private$dataname
                ))
              }
            }
          )

          private$observers$selection <- observeEvent(
            ignoreNULL = FALSE,
            ignoreInit = TRUE,
            eventExpr = input$selection,
            handlerExpr = {
              logger::log_trace(
                sprintf(
                  "LogicalFilterState$server@2 selection of variable %s changed, dataname: %s",
                  private$varname,
                  private$dataname
                )
              )
              # for private$multiple == TRUE input$selection will always have value
              if (is.null(input$selection) && isFALSE(private$multiple)) {
                selection_state <- private$get_selected()
              } else {
                selection_state <- as.logical(input$selection)
              }

              if (is.null(selection_state)) {
                selection_state <- logical(0)
              }
              private$set_selected(selection_state)
            }
          )

          private$keep_na_srv("keep_na")

          logger::log_trace("LogicalFilterState$server initialized, dataname: { private$dataname }")
          NULL
        }
      )
    },
    server_inputs_fixed = function(id) {
      moduleServer(
        id = id,
        function(input, output, session) {
          logger::log_trace("LogicalFilterState$server initializing, dataname: { private$dataname }")

          output$selection <- renderUI({
            countsnow <- unname(table(factor(private$x_reactive(), levels = private$choices)))
            countsmax <- private$choices_counts

            ind <- private$choices %in% private$selected()
            countBars(
              inputId = session$ns("labels"),
              choices = private$selected(),
              countsnow = countsnow[ind],
              countsmax = countsmax[ind]
            )
          })

          logger::log_trace("LogicalFilterState$server initialized, dataname: { private$dataname }")
          NULL
        }
      )
    },

    # @description
    # Server module to display filter summary
    #  renders text describing whether TRUE or FALSE is selected
    #  and if NA are included also
    content_summary = function(id) {
      tagList(
        tags$span(
          class = "filter-card-summary-value",
          toString(private$get_selected())
        ),
        tags$span(
          class = "filter-card-summary-controls",
          if (isTRUE(private$get_keep_na()) && private$na_count > 0) {
            tags$span(
              class = "filter-card-summary-na",
              "NA",
              shiny::icon("check")
            )
          } else if (isFALSE(private$get_keep_na()) && private$na_count > 0) {
            tags$span(
              class = "filter-card-summary-na",
              "NA",
              shiny::icon("xmark")
            )
          } else {
            NULL
          }
        )
      )
    }
  )
)
