#' @name FilterStateExpr
#' @docType class
#'
#'
#' @title `FilterStateExpr` Class
#'
#' @description Class to handle filter expression.
#'
#'
#' @details
#' This class is responsible for displaying filter card and returning filter expression
#'
#' @keywords internal
#'
#' @examples
#' filter_state <- teal.slice:::FilterStateExpr$new(
#'   slice = teal_slice(
#'     dataname = "x",
#'     id = "FA",
#'     title = "Adult females",
#'     expr = "sex == 'F' & age >= 18"
#'   )
#' )
#' filter_state$get_call()
#'
#' # working filter in an app
#' library(shiny)
#' library(shinyjs)
#'
#' ui <- fluidPage(
#'   useShinyjs(),
#'   teal.slice:::include_css_files(pattern = "filter-panel"),
#'   teal.slice:::include_js_files(pattern = "count-bar-labels"),
#'   column(4, div(
#'     h4("ChoicesFilterState"),
#'     filter_state$ui("fs")
#'   )),
#'   column(8, div(
#'     h4("Condition (i.e. call)"), # display the subsetting call generated by this FilterState
#'     textOutput("condition_choices"), br(),
#'     h4("Unformatted state"), # display raw filter state
#'     textOutput("unformatted_choices"), br(),
#'     h4("Formatted state"), # display human readable filter state
#'     textOutput("formatted_choices"), br()
#'   ))
#' )
#'
#' server <- function(input, output, session) {
#'   filter_state$server("fs")
#'   output$condition_choices <- renderPrint(filter_state$get_call())
#'   output$formatted_choices <- renderText(filter_state$format())
#'   output$unformatted_choices <- renderPrint(filter_state$get_state())
#' }
#'
#' if (interactive()) {
#'   shinyApp(ui, server)
#' }
FilterStateExpr <- R6::R6Class( # nolint
  classname = "FilterStateExpr",
  # public methods ----
  public = list(
    #' @description
    #' Initialize a `FilterStateExpr` object
    #' @param slice (`teal_slice_expr`)\cr
    #'   object created by [teal_slice()]
    #' @return `FilterStateExpr`
    initialize = function(slice) {
      checkmate::assert_class(slice, "teal_slice_expr")
      private$teal_slice <- slice
      invisible(self)
    },

    #' @description
    #' Returns a formatted string representing this `FilterStateExpr` object.
    #'
    #' @param show_all `logical(1)` passed to `format.teal_slice`
    #'
    #' @return `character(1)` the formatted string
    #'
    format = function(show_all = FALSE) {
      sprintf(
        "%s:\n%s",
        class(self)[1],
        format(self$get_state(), show_all = show_all)
      )
    },

    #' @description
    #' Prints this `FilterStateExpr` object.
    #'
    #' @param ... additional arguments
    print = function(...) {
      cat(shiny::isolate(self$format(...)))
    },

    #' @description
    #' Returns filtering state.
    #'
    #' @return A `teal_slice` object.
    #'
    get_state = function() {
      private$teal_slice
    },

    #' @description
    #' Sets filtering state.
    #'
    #' @param state a `teal_slice` object
    #'
    #' @return `self` invisibly
    #'
    set_state = function(state) {
      checkmate::assert_class(state, "teal_slice_expr")
      invisible(NULL)
    },

    #' @description
    #' Get reproducible call
    #'
    #' @param dataname (`ignored`) for a consistency with `FilterState`
    #'
    #' Returns reproducible condition call for current selection relevant
    #' for selected variable type.
    #' Method is using internal reactive values which makes it reactive
    #' and must be executed in reactive or isolated context.
    #' @return `language`
    get_call = function(dataname) {
      shiny::isolate(str2lang(private$teal_slice$expr))
    },

    #' @description
    #' Destroy observers stored in `private$observers`.
    #'
    #' @return NULL invisibly
    #'
    destroy_observers = function() {
      lapply(private$observers, function(x) x$destroy())
      invisible(NULL)
    },

    # public shiny modules ----

    #' @description
    #' Shiny module server.
    #'
    #' @param id (`character(1)`)\cr
    #'   shiny module instance id
    #'
    #' @return `moduleServer` function which returns reactive value
    #'   signaling that remove button has been clicked
    #'
    server = function(id) {
      moduleServer(
        id = id,
        function(input, output, session) {
          private$server_summary("summary")
          out <- reactive(input$remove) # back to parent to remove self
          out
        }
      )
    },

    #' @description
    #' Shiny module UI.
    #'
    #' @param id (`character(1)`)\cr
    #'  shiny element (module instance) id;
    #'  the UI for this class contains simple message stating that it is not supported
    #' @param parent_id (`character(1)`) id of the `FilterStates` card container
    ui = function(id, parent_id = "cards") {
      ns <- NS(id)
      shiny::isolate({
        tags$div(
          id = id,
          class = "panel filter-card",
          include_js_files("count-bar-labels.js"),
          tags$div(
            class = "filter-card-header",
            tags$div(
              class = "filter-card-title",
              icon("lock"),
              tags$span(tags$strong(private$teal_slice$id)),
              tags$span(private$teal_slice$title, class = "filter-card-varlabel")
            ),
            tags$div(
              class = "filter-card-controls",
              actionLink(
                inputId = ns("remove"),
                label = icon("circle-xmark", lib = "font-awesome"),
                class = "filter-card-remove"
              )
            ),
            tags$div(
              class = "filter-card-summary",
              private$ui_summary(ns("summary"))
            )
          )
        )
      })
    }
  ),

  # private members ----

  private = list(
    observers = NULL, # stores observers
    teal_slice = NULL, # stores reactiveValues

    # @description
    # Server module to display filter summary
    # @param id `shiny` id parameter
    ui_summary = function(id) {
      ns <- NS(id)
      uiOutput(ns("summary"), class = "filter-card-summary")
    },

    # @description
    # UI module to display filter summary
    # @param shiny `id` parametr passed to moduleServer
    #  renders text describing current state
    server_summary = function(id) {
      moduleServer(
        id = id,
        function(input, output, session) {
          private$content_summary()
        }
      )
    },
    content_summary = function() {
      shiny::isolate(private$teal_slice$expr)
    }
  )
)
